imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    delivery_address: 'webmaster@ice.cam.ac.uk'

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        firephp:
            type:  firephp
            level: info
        mailer:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.mailer.log"
            channels: mailer
            level: debug

assetic:
    use_controller: true

#IceMinervaClient configuration
ice_minerva_client:
    base_url: https://minerva.dev.ice.internal.admin.cam.ac.uk/app_dev.php/

#IceMercuryClient configuration
ice_mercury_client:
    base_url: https://mercury.dev.ice.internal.admin.cam.ac.uk/app_dev.php/api/

#IceVeritasClient configuration
ice_veritas_client:
    base_url: https://veritas.dev.ice.internal.admin.cam.ac.uk/app_dev.php/api/