jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        api_memory:
            memory:
                users:
                    janus: { password: "%janus_api_password%", roles: [ROLE_API_CONSUMER]}

    encoders:
        FOS\UserBundle\Model\UserInterface:
            id: security.encoder.blowfish
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # This is never actually used - it's just required to benefit from the FOSUserBundle management functionality
        fos_user_firewall:
            pattern: ^/fos_user
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
        api:
            pattern: ^/api
            provider: api_memory
            anonymous: ~
            http_basic: ~
        user_authenticate:
            pattern: ^/api/users/authenticate$
            anonymous: false
            form_login: false
            provider: fos_userbundle
            http_basic:
                realm: "ICE user authentication"


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        - { path: ^/api,          roles: ROLE_API_CONSUMER, requires_channel: https }